name: console_menu
description: A menu driven by the console package for command line applications.
version: 0.0.1-dev.2
# homepage: https://www.example.com
repository: https://www.github.com/jhessin/console-menu/

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  console: ^4.1.0
